name: mottai_flutter_app_models
description: Models fro NPO MOTTAI matching app.
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=2.15.1 <3.0.0'
  flutter: '>=1.17.0'

dependencies:
  cloud_firestore: ^3.1.6
  cloud_functions: ^3.2.5
  cupertino_icons: ^1.0.2
  firebase_analytics: ^9.0.5
  firebase_auth: ^3.3.5
  firebase_core: ^1.10.0
  firebase_messaging: ^11.2.5
  firebase_storage: ^10.2.5
  flutter:
    sdk: flutter
  freezed_annotation: ^1.1.0
  json_annotation: ^4.4.0
  ks_flutter_commons:
    path: ../ks_flutter_commons

dev_dependencies:
  build_runner: ^2.1.7
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  freezed: ^1.1.1
  json_serializable: ^6.1.3

flutter:
  uses-material-design: true
