name: mottai_flutter_app_models
description: Models fro NPO MOTTAI matching app.
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=2.15.1 <3.0.0'
  flutter: '>=2.17.0'

dependencies:
  cloud_firestore:
  cloud_functions:
  cupertino_icons:
  firebase_analytics:
  firebase_auth:
  firebase_core:
  firebase_messaging:
  firebase_storage:
  flutter:
    sdk: flutter
  freezed_annotation:
  hooks_riverpod:
  json_annotation:
  ks_flutter_commons:
    path: ../ks_flutter_commons

dev_dependencies:
  build_runner:
  flutter_lints:
  flutter_test:
    sdk: flutter
  freezed:
  json_serializable:

flutter:
  uses-material-design: true
